project 'YWFMDBExamples.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YWFMDBExamples' do
 
pod 'FMDB/SQLCipher'
pod 'YWExcel'

end
